language: generic

matrix:
  include:
  - env: TRAVIS_PYTHON_VERSION=3.6
    os: osx


before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      PY_MAJOR=2 ;
  else
      PY_MAJOR=3 ;
  fi ;
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      OS=Linux ;
  else
      OS=MacOSX ;
  fi ;
- wget https://repo.continuum.io/miniconda/Miniconda$PY_MAJOR-latest-$OS-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda;
- export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH";
- conda config --set always_yes yes --set changeps1 no;
- conda env create --quiet --name cqgui -f cqgui_env.yml
- source activate cqgui
- conda install -c conda-forge pytest=4.0.2 pytest-qt
- pip install pytest-mock pytest-cov codecov
- pip install  pyparsing git+https://github.com/CadQuery/cadquery.git@adam-urbanczyk-OCC-version-update
- conda list
- export DISPLAY=:99.0;
- ( sudo Xvfb :99 -ac -screen 0 1400x900x24 +render +iglx; echo ok )&

before_script:
- ulimit -c unlimited -S 
- sudo rm -f /cores/core.*

script:
- export PYTHONPATH=$(pwd)
- pytest -s --cov=src


after_failure:
- ls /cores/core.* 
- lldb --core `ls /cores/core.*` --batch --one-line "bt"

after_success:
- codecov