jobs:
  test:
    
    environment:
      PYTEST_QT_API: pyqt5
      
    steps:
      - checkout
      - run: cd && rm -rf ~/.pyenv && rm -rf ~/virtualenvs
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
      - run: chmod +x ~/miniconda.sh && ~/miniconda.sh -b
      - run: export PATH="$HOME/miniconda3/bin:$PATH"
      - run: conda config --set always_yes yes
      - run: conda env create --quiet --name cqgui -f cqgui_env.yml
      - run: conda activate $ENVNAME
      - run: pip install pytest-mock pytest-cov codecov
      - run: export PYTHONPATH=$(pwd); pytest -s --cov=src