version: 2

jobs:
  runtests:
  
    macos:
      xcode: "9.0"
    
    environment:
      PYTEST_QT_API: pyqt5
      
    steps:
      - checkout
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install wget
      - run: cd && rm -rf ~/.pyenv && rm -rf ~/virtualenvs
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
      - run: chmod +x ~/miniconda.sh && ~/miniconda.sh -b
      - run: echo "export PATH=~/miniconda3/bin:$PATH" >> $BASH_ENV
      - run: conda config --set always_yes yes
      - run: conda env create --quiet --name cqgui -f cqgui_env.yml
      - run: |
          source activate cqgui
          pip install pytest-mock pytest-cov codecov
          conda env list
          conda list
          export PYTHONPATH=$(pwd):$PYTHONPATH
          echo $PYTHONPATH
          python -c "import PyQt5"
          pytest -s --cov=src
      
workflows:
  version: 2
  
  workflow:
    jobs:
    - runtests