package:
  name: cq-editor
  version:  {{ environ.get('PACKAGE_VERSION') }}

source:
  path: ..

build:
  string: h{{ GIT_DESCRIBE_HASH }}_{{ PKG_BUILDNUM }}
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - cq-editor = cq_editor.__main__:main
    - CQ-editor = cq_editor.__main__:main
requirements:
  build:
    - python >=3.8
    - setuptools

  run:
    - python >=3.8
    - cadquery=master
    - ocp
    - logbook
    - pyqt=5.*
    - pyqtgraph
    - spyder=5.*
    - path
    - logbook
    - requests

test:
  imports:
    - cq_editor

about:
summary: GUI for CadQuery 2
