package:
  name: cq-editor
  version:  {{ environ.get('PACKAGE_VERSION') }}

source:
  path: ..

build:
  string: {{ 'py'+environ.get('PYTHON_VERSION')}}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - cq-editor = cq_editor.__main__:main
    - CQ-editor = cq_editor.__main__:main
requirements:
  build:
    - python {{ environ.get('PYTHON_VERSION') }}
    - setuptools

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - cadquery=master
    - ocp
    - logbook
    - pyqt=5.9.2
    - pyparsing
    - pyqtgraph=0.10.0
    - spyder=3.3.4
    - path.py
    - logbook
    - qtconsole=4.4.4
    - jupyter_client=5.3.4
    - requests

about:
summary: GUI for CadQuery 2.0
