name: build
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Whether to build a single file (onefile) or directory (dir) dist'
        required: true
        default: 'dir'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: 3.8
        activate-environment: test
    - name: Install CadQuery, CQ-editor and pyinstaller
      shell: bash --login {0}
      run: |
        conda info
        conda install -c cadquery -c conda-forge cadquery=master
        conda install -c cadquery -c conda-forge cq-editor=master
        conda install -c conda-forge pyinstaller
        pip install path
    - name: Run build
      shell: bash --login {0}
      run: |
        conda info
        pyinstaller pyinstaller.spec ${{ github.event.inputs.type }}
    - uses: actions/upload-artifact@v2
      with:
        name: CQ-editor-Linux-x86_64
        path: dist
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: 3.8
        activate-environment: test
    - name: Install CadQuery, CQ-editor and pyinstaller
      shell: bash --login {0}
      run: |
        conda info
        conda install -c cadquery -c conda-forge cadquery=master
        conda install -c cadquery -c conda-forge cq-editor=master
        conda install -c conda-forge pyinstaller
        pip install path
        qtdiag
        pip install PyQt5==5.15.1
        qtdiag
    - name: Run build
      shell: bash --login {0}
      run: |
        conda info
        pyinstaller pyinstaller.spec ${{ github.event.inputs.type }}
    - uses: actions/upload-artifact@v2
      with:
        name: CQ-editor-MacOS
        path: dist
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: 3.8
        activate-environment: test
    - name: Install CadQuery and pyinstaller
      shell: powershell
      run: |
        conda list
        conda install -c cadquery -c conda-forge cq-editor=master
        conda install -c anaconda openssl
        conda install -c conda-forge pyinstaller
        pip install pipwin
        pipwin install numpy
        pip install path
        pip install pyopenssl
        Get-Childitem D:\dist* -Recurse
        Copy-Item C:\Miniconda3\envs\test\Library\bin\libssl-1_1-x64.dll  D:\a\_actions\actions\upload-artifact\v2\dist\
        Copy-Item C:\Miniconda3\envs\test\Library\bin\libcrypto-1_1-x64.dll  D:\a\_actions\actions\upload-artifact\v2\dist\
    - name: Run build
      shell: powershell
      run: |
        conda info
        pyinstaller --debug all pyinstaller.spec ${{ github.event.inputs.type }}
    - uses: actions/upload-artifact@v2
      with:
        name: CQ-editor-Windows
        path: dist
